### ISSUE TITLE
attribute error in running algo_gym_stub.py with n_parallel > 1

### ISSUE THREAD

**Issue by barian-do** [openai/rllab#148]
Hi, I'm very new to python, need some help for rllabplusplus-master.

whenever I set the n_parallel parameter >1, I get an error:
AttributeError: 'NoneType' object has no attribute 'run'

More detail is like: (sorry, it looks so messy)
--------------------------------------------------------------------------------------------------------------------------
using seed 1
2017-06-04 08:05:51.032709 KST | Setting seed to 1
2017-06-04 08:05:51.032740 KST | Setting seed to 2
using seed 1
using seed 2
[2017-06-04 08:05:51,091] Making new env: HalfCheetah-v1
2017-06-04 08:05:51.270848 KST | observation space: Box(17,)
2017-06-04 08:05:51.270990 KST | action space: Box(6,)
2017-06-04 08:05:51.385596 KST | Populating workers...
[2017-06-04 08:05:51,440] Making new env: HalfCheetah-v1
[2017-06-04 08:05:51,441] Making new env: HalfCheetah-v1
2017-06-04 08:05:51.628788 KST | observation space: Box(17,)
2017-06-04 08:05:51.628909 KST | action space: Box(6,)
2017-06-04 08:05:51.628920 KST | observation space: Box(17,)
2017-06-04 08:05:51.629025 KST | action space: Box(6,)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/baek/Downloads/rllabplusplus-master_3/rllab/sampler/stateful_pool.py", line 170, in _worker_run_each
    return runner(singleton_pool.G, *args)
  File "/home/baek/Downloads/rllabplusplus-master_3/rllab/sampler/parallel_sampler.py", line 37, in _worker_populate_task
    G.policy = pickle.loads(policy)
  File "/home/baek/Downloads/rllabplusplus-master_3/sandbox/rocky/tf/core/parameterized.py", line 106, in __setstate__
    tf.get_default_session().run(tf.initialize_variables(self.get_params()))
AttributeError: 'NoneType' object has no attribute 'run'

any help, please?

**Comment by dementrock** [comment]
Try creating a session when initializing each worker process, as done in https://github.com/openai/rllab/blob/master/sandbox/rocky/tf/samplers/batch_sampler.py#L19.

In general: rllabplusplus uses a rather outdated commit of rllab. You should either try to merge it with the latest rllab or ask the maintainer of that repo for support.

**Comment by barian-do** [comment]
Thank you so much!
oh, so rllab++ uses some old version? 
It finally runs, what I've done is:
1. delete 'anaconda/envs/rllab3' folder
2. executed 'manual installation' of rllab++
3. I quit using eclipse for rllab++. It keeps returning syntax error, even with rllab3 python3.5 interpreter.
4. used 'pycharm' and it works. -_-. 

so manual installation + pycharm looks good match? 
anyway, Thank you so much again, dementrock for ur help!!

**Comment by dementrock** [comment]
Sounds good, as long as it works :)
