### ISSUE TITLE
Installation error: mujoco-py- "Reason: image not found"

### ISSUE THREAD

**Issue by abhigenie92** [openai/rllab#164]
```
Requirement already satisfied: MarkupSafe>=0.23 in /anaconda/envs/rllab3/lib/python3.5/site-packages (from jinja2->nbconvert->jupyter)
Requirement already satisfied: wcwidth in /anaconda/envs/rllab3/lib/python3.5/site-packages (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter)
Building wheels for collected packages: mujoco-py
  Running setup.py bdist_wheel for mujoco-py ... error
  Complete output from command /anaconda/envs/rllab3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/tmp2cq3l_ompip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py", line 50, in <module>
      cmdclass={'build': Build},
    File "/anaconda/envs/rllab3/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/anaconda/envs/rllab3/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/anaconda/envs/rllab3/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/anaconda/envs/rllab3/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/anaconda/envs/rllab3/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/anaconda/envs/rllab3/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py", line 19, in run
      spec.loader.exec_module(builder)
    File "<frozen importlib._bootstrap_external>", line 665, in exec_module
    File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/builder.py", line 17, in <module>
      from mujoco_py.utils import discover_mujoco
    File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/__init__.py", line 1, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/builder.py", line 296, in <module>
      cymj = load_cython_ext(mjpro_path)
    File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/builder.py", line 57, in load_cython_ext
      mod = imp.load_dynamic("cymj", cext_so_path)
    File "/anaconda/envs/rllab3/lib/python3.5/imp.py", line 342, in load_dynamic
      return _load(spec)
  ImportError: dlopen(/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/generated/cymj_macextensionbuilder.so, 2): Library not loaded: /Users/pw/.mujoco/mjpro150/bin/libmujoco150.dylib
    Referenced from: /private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/generated/cymj_macextensionbuilder.so
    Reason: image not found

  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py, cached-property, line-profiler, cloudpickle, redis, Theano, pyyaml, keras, Lasagne, certifi, urllib3, idna, chardet, requests, plotly, colorama, pyasn1, rsa, awscli, pyglet, gym, qtconsole, jupyter-console, jupyter, python-utils, progressbar2, filelock, nose, protobuf, chainer, tensorflow-gpu, nine, numpy-stl, nibabel, pylru, networkx, future, pymongo, hyperopt, pbr, mock, py, pytest, polling, enum34, markdown, backports.weakref, html5lib, tensorflow, prettytensor
  Running setup.py install for mujoco-py ... error
    Complete output from command /anaconda/envs/rllab3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-c9l9_7kj-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py", line 50, in <module>
        cmdclass={'build': Build},
      File "/anaconda/envs/rllab3/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda/envs/rllab3/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/anaconda/envs/rllab3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda/envs/rllab3/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/anaconda/envs/rllab3/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/anaconda/envs/rllab3/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda/envs/rllab3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py", line 19, in run
        spec.loader.exec_module(builder)
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/builder.py", line 17, in <module>
        from mujoco_py.utils import discover_mujoco
      File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/__init__.py", line 1, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/builder.py", line 296, in <module>
        cymj = load_cython_ext(mjpro_path)
      File "/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/builder.py", line 57, in load_cython_ext
        mod = imp.load_dynamic("cymj", cext_so_path)
      File "/anaconda/envs/rllab3/lib/python3.5/imp.py", line 342, in load_dynamic
        return _load(spec)
    ImportError: dlopen(/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/generated/cymj_macextensionbuilder.so, 2): Library not loaded: /Users/pw/.mujoco/mjpro150/bin/libmujoco150.dylib
      Referenced from: /private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/mujoco_py/generated/cymj_macextensionbuilder.so
      Reason: image not found

    ----------------------------------------
Command "/anaconda/envs/rllab3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-c9l9_7kj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/04/6jnvdfp1143gg33j6pbyphdh0000gn/T/pip-build-sl4s5h6w/mujoco-py/

CondaValueError: pip returned an error.

Conda environment created! Make sure to run `source activate rllab3` whenever you open a new terminal and want to run programs under rllab.
```
When .I try to install on mac os x.

**Comment by dementrock** [comment]
The key error is this one: `Library not loaded: /Users/pw/.mujoco/mjpro150/bin/libmujoco150.dylib`

You need to have mujoco set up on your machine. See instructions at https://github.com/openai/mujoco-py

**Comment by SJTUGuofei** [comment]
When I install the mujoco, I have the following error:
Please enter the path to the mujoco zip file [mjpro131_linux.zip]:~/Downloads/
No file found at ~/Downloads/

But I just put the mjpro131_linux.zip file under the Downloads folder, could you help me? 
Thx

**Comment by Beckschen** [comment]
@SJTUGuofei  hello, I met the same prob with you. Did you know how to fix it?

**Comment by AntonioSerrano** [comment]
I had a similar problem in my Mac. Typing `pip3 install -U 'mujoco-py<1.50.2,>=1.50.1'` threw the error `Library not loaded: /Users/woj/.mujoco/mjpro150/bin/libmujoco150.dylib`. I wrote to Wojciech from the developer team and he gave the following solution. It worked for me. I hope it works for you too:

`pip3 install mujoco-py==1.50.1.36`
