### ISSUE TITLE
centOS MemoryError

### ISSUE THREAD

**Issue by weiliu620** [openai/rllab#167]
I'm on CentOS 7, Anaconda python 3.5.2, Theano 0.9. When running the trpo_cartpole_picked.py example, I got the follow error (no error if I run it in Ubuntu 14 docker image created by dockerfile under 'docker' folder). 

Any insights on this issue? 
```
(rllab3) weiliu@localhost:~/projects/rl_learning$ python ../rllab/examples/trpo_cartpole_pickled.py
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 6021)
/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py:631: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn(warn)
/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
python /home/weiliu/projects/rllab/scripts/run_experiment_lite.py  --plot 'True'  --use_cloudpickle 'True'  --exp_name 'experiment_2017_07_10_15_22_11_0001'  --snapshot_mode 'last'  --variant_data 'gAN9cQBYCAAAAGV4cF9uYW1lcQFYIwAAAGV4cGVyaW1lbnRfMjAxN18wN18xMF8xNV8yMl8xMV8wMDAxcQJzLg=='  --log_dir '/home/weiliu/projects/rllab/home/weiliu/projects/rl_learning/explog/local/experiment/experiment_2017_07_10_15_22_11_0001'  --n_parallel '2'  --args_data 'gAJjY2xvdWRwaWNrbGUuY2xvdWRwaWNrbGUKX2ZpbGxfZnVuY3Rpb24KcQAoY2Nsb3VkcGlja2xlLmNsb3VkcGlja2xlCl9tYWtlX3NrZWxfZnVuYwpxAWNjbG91ZHBpY2tsZS5jbG91ZHBpY2tsZQpfYnVpbHRpbl90eXBlCnECWAgAAABDb2RlVHlwZXEDhXEEUnEFKEsASwBLBUsTS0djX2NvZGVjcwplbmNvZGUKcQZYjAAAAHQAAHQBAMKDAADCgwEAfQEAdAIAZAEAfAEAagMAZAIAZBMAwoMAAn0CAHQEAGQBAHwBAGoDAMKDAAF9AwB0BQBkBAB8AQBkBQB8AgBkBgB8AwBkBwBkCABkCQBkCgBkCwBkDABkDQBkDgBkDwBkEABkEQBkEgDCgwAJfQQAfAQAagYAwoMAAAFkAABTcQdYBgAAAGxhdGluMXEIhnEJUnEKKE5YCAAAAGVudl9zcGVjcQtYDAAAAGhpZGRlbl9zaXplc3EMSyBYAwAAAGVudnENWAYAAABwb2xpY3lxDlgIAAAAYmFzZWxpbmVxD1gKAAAAYmF0Y2hfc2l6ZXEQTaAPWA8AAABtYXhfcGF0aF9sZW5ndGhxEUtkWAUAAABuX2l0cnESTegDWAgAAABkaXNjb3VudHETRz/vrhR64UeuWAkAAABzdGVwX3NpemVxFEc/hHrhR64Ue1gEAAAAcGxvdHEViEsgSyCGcRZ0cRcoWAkAAABub3JtYWxpemVxGFgLAAAAQ2FydHBvbGVFbnZxGVgRAAAAR2F1c3NpYW5NTFBQb2xpY3lxGlgEAAAAc3BlY3EbWBUAAABMaW5lYXJGZWF0dXJlQmFzZWxpbmVxHFgEAAAAVFJQT3EdWAUAAAB0cmFpbnEedHEfKFgBAAAAX3EgaA1oDmgPWAQAAABhbGdvcSF0cSJYKgAAAC4uL3JsbGFiL2V4YW1wbGVzL3RycG9fY2FydHBvbGVfcGlja2xlZC5weXEjWAgAAABydW5fdGFza3EkSwloBlggAAAAAAEPAgYBCQIJAxICBgEGAQYBBgEGAQYBBgEGAQYCCQJxJWgIhnEmUnEnKSl0cShScSlK/////31xKodxK1JxLH1xLShoGGNybGxhYi5lbnZzLm5vcm1hbGl6ZWRfZW52Ck5vcm1hbGl6ZWRFbnYKcS5oHGNybGxhYi5iYXNlbGluZXMubGluZWFyX2ZlYXR1cmVfYmFzZWxpbmUKTGluZWFyRmVhdHVyZUJhc2VsaW5lCnEvaBpjcmxsYWIucG9saWNpZXMuZ2F1c3NpYW5fbWxwX3BvbGljeQpHYXVzc2lhbk1MUFBvbGljeQpxMGgZY3JsbGFiLmVudnMuYm94MmQuY2FydHBvbGVfZW52CkNhcnRwb2xlRW52CnExaB1jcmxsYWIuYWxnb3MudHJwbwpUUlBPCnEydU59cTNOdFIu'  --seed '1'
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 6021)
/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py:631: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn(warn)
/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
using seed 1
2017-07-10 15:22:16.781107 EDT | [experiment_2017_07_10_15_22_11_0001] Populating workers...
2017-07-10 15:22:16.781379 EDT | [experiment_2017_07_10_15_22_11_0001] Populated
Error when trying to find the memory information on the GPU: initialization error
Error allocating 512 bytes of device memory (initialization error). Driver report 0 bytes free and 0 bytes total 
Process Process-1:
Traceback (most recent call last):
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weiliu/projects/rllab/rllab/plotter/plotter.py", line 27, in _worker_start
    msg = queue.get_nowait()
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/multiprocessing/queues.py", line 126, in get_nowait
    return self.get(False)
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
  File "/home/weiliu/projects/rllab/rllab/core/parameterized.py", line 81, in __setstate__
    Serializable.__setstate__(self, d)
  File "/home/weiliu/projects/rllab/rllab/core/serializable.py", line 46, in __setstate__
    out = type(self)(**dict(zip(in_order_args, d["__args"]), **d["__kwargs"]))
  File "/home/weiliu/projects/rllab/rllab/policies/gaussian_mlp_policy.py", line 67, in __init__
    output_nonlinearity=output_nonlinearity,
  File "/home/weiliu/projects/rllab/rllab/core/network.py", line 62, in __init__
    b=hidden_b_init,
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/lasagne/layers/dense.py", line 71, in __init__
    self.W = self.add_param(W, (num_inputs, num_units), name="W")
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/lasagne/layers/base.py", line 215, in add_param
    param = utils.create_param(spec, shape, name)
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/lasagne/utils.py", line 362, in create_param
    return theano.shared(arr, name=name)
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/theano/compile/sharedvalue.py", line 268, in shared
    allow_downcast=allow_downcast, **kwargs)
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/site-packages/theano/sandbox/cuda/var.py", line 188, in float32_shared_constructor
    deviceval = type_support_filter(value, type.broadcastable, False, None)
MemoryError: ('Error allocating 512 bytes of device memory (initialization error).', "you might consider using 'theano.shared(..., borrow=True)'")
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:02
2017-07-10 15:22:19.382260 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | fitting baseline...
2017-07-10 15:22:19.394938 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | fitted
=: Compiling function f_loss
done in 0.519 seconds
=: Compiling function constraint
done in 0.268 seconds
2017-07-10 15:22:20.190878 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | computing loss before
2017-07-10 15:22:20.193312 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | performing update
2017-07-10 15:22:20.193510 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | computing descent direction
=: Compiling function f_grad
done in 0.654 seconds
=: Compiling function f_Hx_plain
done in 1.314 seconds
2017-07-10 15:22:22.394595 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | descent direction computed
=: Compiling function f_loss_constraint
done in 0.499 seconds
2017-07-10 15:22:22.896620 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | backtrack iters: 0
2017-07-10 15:22:22.896843 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | computing loss after
2017-07-10 15:22:22.896992 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | optimization finished
2017-07-10 15:22:22.900769 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | saving snapshot...
2017-07-10 15:22:22.903141 EDT | [experiment_2017_07_10_15_22_11_0001] itr #0 | saved
2017-07-10 15:22:22.903813 EDT | -----------------------  -------------
2017-07-10 15:22:22.903990 EDT | Iteration                  0
2017-07-10 15:22:22.904136 EDT | AverageDiscountedReturn   70.8384
2017-07-10 15:22:22.904276 EDT | AverageReturn             74.6689
2017-07-10 15:22:22.904414 EDT | ExplainedVariance          4.2123e-12
2017-07-10 15:22:22.904551 EDT | NumTrajs                 473
2017-07-10 15:22:22.904687 EDT | Entropy                    1.41894
2017-07-10 15:22:22.904839 EDT | Perplexity                 4.13273
2017-07-10 15:22:22.904977 EDT | StdReturn                 56.5064
2017-07-10 15:22:22.905112 EDT | MaxReturn                319.869
2017-07-10 15:22:22.905246 EDT | MinReturn                  0
2017-07-10 15:22:22.905374 EDT | AveragePolicyStd           1
2017-07-10 15:22:22.905507 EDT | LossBefore                 5.89468e-09
2017-07-10 15:22:22.905634 EDT | LossAfter                 -0.0140345
2017-07-10 15:22:22.905768 EDT | MeanKLBefore               0
2017-07-10 15:22:22.905921 EDT | MeanKL                     0.00374796
2017-07-10 15:22:22.906056 EDT | dLoss                      0.0140345
2017-07-10 15:22:22.906190 EDT | RunningTime                6.03966
2017-07-10 15:22:22.906325 EDT | -----------------------  -------------
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:02
2017-07-10 15:22:25.462317 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | fitting baseline...
2017-07-10 15:22:25.471745 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | fitted
2017-07-10 15:22:25.478262 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | computing loss before
2017-07-10 15:22:25.480347 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | performing update
2017-07-10 15:22:25.480517 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | computing descent direction
2017-07-10 15:22:25.543759 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | descent direction computed
2017-07-10 15:22:25.548717 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | backtrack iters: 1
2017-07-10 15:22:25.548901 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | computing loss after
2017-07-10 15:22:25.549048 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | optimization finished
2017-07-10 15:22:25.552771 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | saving snapshot...
2017-07-10 15:22:25.555092 EDT | [experiment_2017_07_10_15_22_11_0001] itr #1 | saved
2017-07-10 15:22:25.555740 EDT | -----------------------  -------------
2017-07-10 15:22:25.555923 EDT | Iteration                  1
2017-07-10 15:22:25.556105 EDT | AverageDiscountedReturn   68.302
2017-07-10 15:22:25.556365 EDT | AverageReturn             72.1463
2017-07-10 15:22:25.556539 EDT | ExplainedVariance          0.124835
2017-07-10 15:22:25.556692 EDT | NumTrajs                 488
2017-07-10 15:22:25.556846 EDT | Entropy                    1.41031
2017-07-10 15:22:25.556996 EDT | Perplexity                 4.09722
2017-07-10 15:22:25.557138 EDT | StdReturn                 60.1451
2017-07-10 15:22:25.557272 EDT | MaxReturn                409.816
2017-07-10 15:22:25.557402 EDT | MinReturn                  0
2017-07-10 15:22:25.557537 EDT | AveragePolicyStd           0.991408
2017-07-10 15:22:25.557673 EDT | LossBefore                 4.88275e-09
2017-07-10 15:22:25.557815 EDT | LossAfter                 -0.0353225
2017-07-10 15:22:25.557953 EDT | MeanKLBefore              -2.17587e-08
2017-07-10 15:22:25.558082 EDT | MeanKL                     0.00745141
2017-07-10 15:22:25.558209 EDT | dLoss                      0.0353225
2017-07-10 15:22:25.558337 EDT | RunningTime                8.69161
2017-07-10 15:22:25.558469 EDT | -----------------------  -------------
0% [########                      ] 100% | ETA: 00:00:01^CTraceback (most recent call last):
  File "../rllab/examples/trpo_cartpole_pickled.py", line 44, in <module>
    plot=True
  File "/home/weiliu/projects/rllab/rllab/misc/instrument.py", line 493, in run_experiment_lite
    command, shell=True, env=dict(os.environ, **env))
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/subprocess.py", line 559, in call
    return p.wait(timeout=timeout)
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/weiliu/anaconda3/envs/rllab3/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by dementrock** [comment]
Seems like it's trying to use gpu on a sampling thread. For such a small problem you don't really need gpu, and you can force it to use cpu by prepending `THEANO_FLAGS='device=cpu'`

**Comment by weiliu620** [comment]
Thanks a lot. Yes that's a small problem, but I'm trying to benchmarking cpu vs gpu, so I set up gpu for this purpose. Do you have empirical comparison results about whether/how much gpu is faster than cpu version? (it's problem dependent, I know)

**Comment by dementrock** [comment]
For small problems, if the environment time is significant, it won't help much. It may help in problems where either sampling is extremely fast, or if the network is huge.
