### ISSUE TITLE
run trpo_cartpole fail on Mac

### ISSUE THREAD

**Issue by lchenat** [openai/rllab#51]
RLLAB works fine on the sentOS server, but it does not work on my MAC. When I ran trpo_cartpole.py in examples it stuck here and made no progress:

python trpo_cartpole.py

/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")

I press Ctrl + C and it shows:

^CTraceback (most recent call last):
  File "trpo_cartpole.py", line 12, in <module>
    hidden_sizes=(32, 32)
  File "/Users/lchenat/Desktop/FYT/rllab/rllab/policies/gaussian_mlp_policy.py", line 115, in __init__
    outputs=[mean_var, log_std_var],
  File "/Users/lchenat/Desktop/FYT/rllab/rllab/misc/ext.py", line 135, in compile_function
    **kwargs
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1456, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1879, in apply
    nb += self.process_node(fgraph, node)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/tensor/opt.py", line 5825, in constant_folding
    no_recycling=[])
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2182, in compile_str
    p_out = output_subprocess_Popen(cmd)
  File "/Users/lchenat/anaconda2/lib/python2.7/site-packages/theano/misc/windows.py", line 78, in output_subprocess_Popen
    out = p.communicate()
  File "/Users/lchenat/anaconda2/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/Users/lchenat/anaconda2/lib/python2.7/subprocess.py", line 1417, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/Users/lchenat/anaconda2/lib/python2.7/subprocess.py", line 1471, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt

I already upgraded my RLLAB to the latest version.

**Comment by dementrock** [comment]
Seems like you are still using python 2. Could you try python 3?
