### ISSUE TITLE
Cannot import name 'monitor' for trpo_gym

### ISSUE THREAD

**Issue by ashwinreddy** [openai/rllab#67]
I successfully installed rllab, and the trpo_cartpole.py example worked fine, but I'm getting an error with trpo_gym.py:
```
Traceback (most recent call last):
  File "trpo_gym.py", line 6, in <module>
    from rllab.envs.gym_env import GymEnv
  File "/home/ashwin/Research/rllab/rllab/envs/gym_env.py", line 4, in <module>
    from gym.monitoring import monitor
ImportError: cannot import name 'monitor'
```
I was looking at the latest Gym source code and `gym.monitoring` is definitely there but I can't find any `monitor` method or class.

**Comment by dementrock** [comment]
Sorry for the late reply! There has been some updates made to the gym repo. Should be fixed in 142b68ddb907f4b3c7e50b4f2299127296d7ce74.

**Comment by AjayTalati** [comment]
Oh dear :(  , seems like it might be broken again?

```
Traceback (most recent call last):
  File "./examples/trpo_gym.py", line 3, in <module>
    from rllab.envs.gym_env import GymEnv
  File "/home/ajay/PythonProjects/rllab/rllab/envs/gym_env.py", line 5, in <module>
    from gym.monitoring import monitor_manager
ImportError: cannot import name 'monitor_manager' 
```

**Comment by dementrock** [comment]
Fixed!

**Comment by AjayTalati** [comment]
Fan Q :)

**Comment by dementrock** [comment]
Hi @AjayTalati, yes we are working on the code release :) It has been delayed mostly because the first-order modifications to TRPO is waiting to be released separately. The learning to reinforcement learn paper has very similar ideas (except the learning algorithm used), so if you'd like to work on any follow-up ideas, your linked repo could be a good starting point.

**Comment by leduckhc** [comment]
Hi I am using the most recent gym 0.7.3 and it raises an error `self.env._monitor.stats_recorder` does not exist. After removing `_monitor` it raises another error `gym.error.ResetNeeded: Trying to step environment which is currently done. While the monitor is active for SpaceInvaders-v0, you cannot step beyond the end of an episode. Call 'env.reset()' to start the next episode. While I set `force_reset=True`
`

**Comment by serteckian** [comment]
Hi,
I am getting this same error with trpo_gym.py: 
`Traceback (most recent call last):
  File "/home/love/rl/rllab/examples/trpo_gym.py", line 6, in <module>
    from rllab.envs.gym_env import GymEnv
  File "/home/love/rl/rllab/rllab/envs/gym_env.py", line 4, in <module>
    from gym.monitoring import monitor
ImportError: cannot import name 'monitor'
`
Any quick fix?
Thanks!

**Comment by dementrock** [comment]
@serteckian Make sure you are using the latest rllab code?

**Comment by chelseas** [comment]
This fixed things for me:
from gym.wrappers.monitor import Monitor
