### ISSUE TITLE
Registration issues with custom gym environment in stub mode

### ISSUE THREAD

**Issue by WesleyHsieh** [openai/rllab#68]
I'm attempting to run TRPO on a custom Gym environment (not included with default installation). There seems to be an issue with environment registration in stub mode when running the experiment that doesn't happen normally, even after confirming that the environment is properly registered.

Running the following code without stub mode works fine as-is.

```
from rllab.algos.trpo import TRPO
from rllab.baselines.linear_feature_baseline import LinearFeatureBaseline
from rllab.envs.gym_env import GymEnv
from rllab.envs.normalized_env import normalize
from rllab.misc.instrument import stub, run_experiment_lite
from rllab.policies.gaussian_mlp_policy import GaussianMLPPolicy
from rllab.policies.categorical_mlp_policy import CategoricalMLPPolicy

import gym_driving

# stub(globals())

env = GymEnv('DrivingEnv-v0')

policy = CategoricalMLPPolicy(
    env_spec=env.spec,
    # The neural network policy should have two hidden layers, each with 32 hidden units.
    hidden_sizes=(32, 32)
)

baseline = LinearFeatureBaseline(env_spec=env.spec)

algo = TRPO(
    env=env,
    policy=policy,
    baseline=baseline,
    batch_size=1000,
    max_path_length=env.horizon,
    n_itr=10,
    discount=0.99,
    step_size=0.01,
    # Uncomment both lines (this and the plot parameter below) to enable plotting
    # plot=True,
)

algo.train()

# run_experiment_lite(
#     algo.train(),
#     # Number of parallel workers for sampling
#     n_parallel=-1,
#     # Only keep the snapshot parameters for the last iteration
#     snapshot_mode="last",
#     # Specifies the seed for the experiment. If this is not provided, a random seed
#     # will be used
#     seed=1,
#     # plot=True,
# )
```

However, running in stub mode (commenting the algo.train() and uncommenting the stub(globals()) and run_experiment_lite() lines) has issues with registering the environment and returns the following error.

```
 (rllab3) wesley@wesley-HP-Notebook:~/install/rllab/examples$ python custom_gym_env_trpo.py 
/home/wesley/anaconda2/envs/rllab3/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
python /home/wesley/install/rllab/scripts/run_experiment_lite.py  --n_parallel '-1'  --log_dir '/home/wesley/install/rllab/data/local/experiment/experiment_2017_01_08_23_24_10_0001'  --args_data 'gANjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJNZXRob2RDYWxsCnEAKYFxAX1xAihYCAAAAF9fa3dhcmdzcQN9cQRYBgAAAF9fYXJnc3EFKGNybGxhYi5taXNjLmluc3RydW1lbnQKU3R1Yk9iamVjdApxBimBcQd9cQgoWAYAAABrd2FyZ3NxCX1xCihYCAAAAGRpc2NvdW50cQtHP++uFHrhR65YAwAAAGVudnEMaAYpgXENfXEOKGgJfXEPWAgAAABlbnZfbmFtZXEQWA0AAABEcml2aW5nRW52LXYwcRFzWAsAAABwcm94eV9jbGFzc3ESY3JsbGFiLmVudnMuZ3ltX2VudgpHeW1FbnYKcRNYBAAAAGFyZ3NxFCl1YlgFAAAAbl9pdHJxFUsKWAgAAABiYXNlbGluZXEWaAYpgXEXfXEYKGgJfXEZWAgAAABlbnZfc3BlY3EaY3JsbGFiLm1pc2MuaW5zdHJ1bWVudApTdHViQXR0cgpxGymBcRx9cR0oWAoAAABfYXR0cl9uYW1lcR5YBAAAAHNwZWNxH1gEAAAAX29ianEgaA11YnNoEmNybGxhYi5iYXNlbGluZXMubGluZWFyX2ZlYXR1cmVfYmFzZWxpbmUKTGluZWFyRmVhdHVyZUJhc2VsaW5lCnEhaBQpdWJYDwAAAG1heF9wYXRoX2xlbmd0aHEiaBspgXEjfXEkKGgeWAcAAABob3Jpem9ucSVoIGgNdWJYCQAAAHN0ZXBfc2l6ZXEmRz+EeuFHrhR7WAoAAABiYXRjaF9zaXplcSdN6ANYBgAAAHBvbGljeXEoaAYpgXEpfXEqKGgJfXErKGgaaBspgXEsfXEtKGgeaB9oIGgNdWJYDAAAAGhpZGRlbl9zaXplc3EuSyBLIIZxL3VoEmNybGxhYi5wb2xpY2llcy5jYXRlZ29yaWNhbF9tbHBfcG9saWN5CkNhdGVnb3JpY2FsTUxQUG9saWN5CnEwaBQpdWJ1aBJjcmxsYWIuYWxnb3MudHJwbwpUUlBPCnExaBQpdWJYBQAAAHRyYWlucTIpfXEzdHE0dWIu'  --exp_name 'experiment_2017_01_08_23_24_10_0001'  --snapshot_mode 'last'  --seed '1'  --use_cloudpickle 'False'
/home/wesley/anaconda2/envs/rllab3/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
using seed 1
[2017-01-08 23:24:12,277] Making new env: DrivingEnv-v0
Error while instantiating <class 'rllab.envs.gym_env.GymEnv'>
Traceback (most recent call last):
  File "/home/wesley/anaconda2/envs/rllab3/lib/python3.5/site-packages/gym/envs/registration.py", line 116, in spec
    return self.env_specs[id]
KeyError: 'DrivingEnv-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1226, in concretize
    *args, **kwargs)
  File "/home/wesley/install/rllab/rllab/envs/gym_env.py", line 57, in __init__
    env = gym.envs.make(env_name)
  File "/home/wesley/anaconda2/envs/rllab3/lib/python3.5/site-packages/gym/envs/registration.py", line 140, in make
    return registry.make(id)
  File "/home/wesley/anaconda2/envs/rllab3/lib/python3.5/site-packages/gym/envs/registration.py", line 104, in make
    spec = self.spec(id)
  File "/home/wesley/anaconda2/envs/rllab3/lib/python3.5/site-packages/gym/envs/registration.py", line 126, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: DrivingEnv-v0
Traceback (most recent call last):
  File "/home/wesley/install/rllab/scripts/run_experiment_lite.py", line 136, in <module>
    run_experiment(sys.argv)
  File "/home/wesley/install/rllab/scripts/run_experiment_lite.py", line 123, in run_experiment
    maybe_iter = concretize(data)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1208, in concretize
    obj = concretize(maybe_stub.obj)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1223, in concretize
    kwargs = concretize(maybe_stub.kwargs)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1238, in concretize
    ret[concretize(k)] = concretize(v)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1223, in concretize
    kwargs = concretize(maybe_stub.kwargs)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1238, in concretize
    ret[concretize(k)] = concretize(v)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1216, in concretize
    obj = concretize(maybe_stub.obj)
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 1232, in concretize
    ret = maybe_stub.__stub_cache
  File "/home/wesley/install/rllab/rllab/misc/instrument.py", line 158, in __getattr__
    raise AttributeError('Cannot get attribute %s from %s' % (item, self.proxy_class))
AttributeError: Cannot get attribute __stub_cache from <class 'rllab.envs.gym_env.GymEnv'>
```

Adding the following lines somewhere after the "import gym_driving" line (both with and without stub mode) confirms that the environment is registered even during stub mode.
```
from gym.envs.registration import spec

print(spec('DrivingEnv-v0'))
```

Any ideas on how to ensure the environment properly registers when running the experiment?

**Comment by leduckhc** [comment]
Hi, I've been been googling DrivingEnv-v0 unfortunately, I was neither be able to find one nor install gym_driving. The stack tells the problem obviously is with DrivingEnv-v0. It has to be that.

Anyway, I see `n_parallel=(minus)-1` which is strange to me.

**Comment by dementrock** [comment]
This is because of the way `stub` works, which is not very intuitive. What happens here is that the `import gym_driving` statement is not getting called in each of the spawned processes. I have updated the doc to introduce the newer mode for running experiments: https://rllab.readthedocs.io/en/latest/user/experiments.html#pickled-mode-experiments

In this mode you will write the import statement inside the `run_task` method call, and it should work.

**Comment by Deams51** [comment]
@dementrock 
Adding the import statement to the `run_task` does work when using only 1 parallel worker. 
But the problem persists when `n_parallel` is superior to 1. 

`
def run_task(*_):
    import gym_myawesomegym
    env = normalize(GymEnv("Myawesomegym-v0", force_reset=True))

    policy = CategoricalMLPPolicy(
        env_spec=env.spec,
        hidden_sizes=(32, 32)
    )

    baseline = LinearFeatureBaseline(env_spec=env.spec)

    algo = TRPO(
        env=env,
        policy=policy,
        baseline=baseline,
        batch_size=4000,
        max_path_length=100,
        n_itr=1000,
        discount=0.99,
        step_size=0.01,
    )
    algo.train()


run_experiment_lite(
    run_task,
    n_parallel=2,
    snapshot_mode="last",
    seed=1,
)`

**Comment by florianshkurti** [comment]
Confirming that the problem persists when `n_parallel > 1`. It also occurs when` plot=True`, regardless of the value of `n_parallel`.

**Comment by eugenevinitsky** [comment]
Just in case it helps anyone, I moved the registration into the initializer for GymEnv and that resolved the issue.
