### ISSUE TITLE
Params.json missing

### ISSUE THREAD

**Issue by leduckhc** [openai/rllab#74]
Hi, when running experiments. I cannot find a file params.json generated anymore. Is it a bug or am I missing something? I tried viskit and it does not generate any graph. It shows an error that params.json cannot be loaded. It gets me curious.

**Comment by dementrock** [comment]
You should specify the variant dict instead for the newest way of running experiments. See https://github.com/openai/rllab/blob/master/examples/cluster_demo.py#L50. I've changed the script so that if you still use `stub()`, it should generate the params.json file as before.

**Comment by bichengcao** [comment]
I ran `python examples/trpo_gym.py`.
Then when I do `scripts/submit_gym.py` it also gives me this error:

```
Traceback (most recent call last):
  File "scripts/submit_gym.py", line 22, in <module>
    params_json = load_params(params_file_path)
  File "/Users/bichengcao/Projects/rllab/rllab/viskit/core.py", line 73, in load_params
    with open(params_json_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bichengcao/Projects/rllab/data/local/experiment/experiment_2017_02_22_22_43_02_0001/params.json'
```

**Comment by dementrock** [comment]
I see. Just remove that line. The value is not used.

**Comment by guyfre** [comment]
Hi,
I try to use stub mode so I could have the params.json and then could continue the training.
When I run this:
/-------------------------------------
from rllab.algos.trpo import TRPO
from rllab.baselines.zero_baseline import ZeroBaseline
from rllab.envs.ABEnv import ABEnv
from rllab.envs.normalized_env import normalize
from rllab.policies.gaussian_mlp_policy import GaussianMLPPolicy
from rllab.misc.instrument import run_experiment_lite, stub

stub(globals())

def run_task(*_):

    #define the port to use with the java server
    ABEnv.port = 5555
    env = normalize(ABEnv())
    policy = GaussianMLPPolicy(
        env_spec=env.spec,
        hidden_sizes=(10,10,10),
        std_hidden_sizes=(10,10,10),
    )
    baseline = ZeroBaseline(env_spec=env.spec)
    algo = TRPO(
        env=env,
        policy=policy,
        baseline=baseline,
        batch_size=1,
        n_itr=1000,
    )
    algo.train()


run_experiment_lite(
    run_task,
    # Number of parallel workers for sampling
    n_parallel=1,
    # Only keep the snapshot parameters for the last iteration
    snapshot_mode="last",
    # Specifies the seed for the experiment. If this is not provided, a random seed
    # will be used
    seed=1,
    # plot=True,
)
/--------------------------
the process ends after init. output:
.
.
.
using seed 1
2017-04-24 02:15:59.006516 PDT | Setting seed to 1
using seed 1
(rllab3) guy@ubuntu:~/PROJECT/rllab-master$ 
If I comment the "stub(globals())" line then it works but generates params.pkl file and if I want to continue training with  scripts/resume_training.py and save the progress I can't do it because passing --log_dir flag isn't relevant because I get the "Failed to find json file. Continuing in non-stub mode..." exception. I don't understand what to do in order to save the progress multiple times and not only at the first time...

**Comment by guilhermecano** [comment]
I have got the same problem. The stub mode simply doesn't work, and if try to comment the stub(globals()) line, I get the same exception  "Failed to find json file. Continuing in non-stub mode...".
Has anyone solved it by now?
