### ISSUE TITLE
Trouble Integrating with OpenAI

### ISSUE THREAD

**Issue by dqii** [openai/rllab#80]
Hi, I'm having a lot of trouble integrating rllab with OpenAI. Specifically, I'm trying to modify ddpg_cartpole.py to work with CarRacing-v0.

https://rllab.readthedocs.io/en/latest/user/gym_integration.html
I integrated the OpenAI environment after following these instructions, but I'm not sure how to work with this error, which is similar to @56

Traceback (most recent call last):
  File "/Users/diqi/iw_s17/rllab/scripts/run_experiment_lite.py", line 136, in <module>
    run_experiment(sys.argv)
  File "/Users/diqi/iw_s17/rllab/scripts/run_experiment_lite.py", line 120, in run_experiment
    method_call(variant_data)
  File "examples/ddpg_car.py", line 42, in run_task
    algo.train()
  File "/Users/diqi/iw_s17/rllab/rllab/algos/ddpg.py", line 221, in train
    observation = self.env.reset()
  File "/Users/diqi/iw_s17/rllab/rllab/envs/normalized_env.py", line 52, in reset
    ret = self._wrapped_env.reset()
  File "/Users/diqi/iw_s17/rllab/rllab/envs/gym_env.py", line 108, in reset
    return self.env.reset()
  File "/Users/diqi/anaconda/envs/rllab3/lib/python3.5/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Users/diqi/anaconda/envs/rllab3/lib/python3.5/site-packages/gym/wrappers/monitoring.py", line 39, in _reset
    self._before_reset()
  File "/Users/diqi/anaconda/envs/rllab3/lib/python3.5/site-packages/gym/wrappers/monitoring.py", line 190, in _before_reset
    self.stats_recorder.before_reset()
  File "/Users/diqi/anaconda/envs/rllab3/lib/python3.5/site-packages/gym/monitoring/stats_recorder.py", line 68, in before_reset
    raise error.Error("Tried to reset environment which is not done. While the monitor is active for {}, you cannot call reset() unless the episode is over.".format(self.env_id))

**Comment by dementrock** [comment]
Hi @dqii, try setting force_reset to True in the arguments of GymEnv.

**Comment by dementrock** [comment]
Fixed again (this hack uses the private interface of gym, which seems to change quite frequently). Pull from latest master.

Also I freezed the version of gym in environment.yml. Make sure your version of gym matches the commit (93d554bdbb4b2d29ff1a685158dbde93b36e3801).
