### ISSUE TITLE
Error in GaussianMLPPolicy's get_actions() method

### ISSUE THREAD

**Issue by sarvjeetsinghghotra** [openai/rllab#81]
``` python
policy = GaussianMLPPolicy(env_spec=e.spec, hidden_sizes=hidden_sizes)
>>> e = GymEnv('Hopper-v1')
>>> hidden_sizes = (32, 32)
>>> o = e.reset()
>>> policy.get_action(o)
(array([ 0.6878297 ,  1.49804142,  0.07628284]), {'log_std': array([ 0.,  0.,  0.]), 'mean': array([-0.1323408 , -0.20070054,  0.43206595])})
>>> policy.get_actions(o)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sarv/summer16/rllab/rllab/policies/gaussian_mlp_policy.py", line 141, in get_actions
    means, log_stds = self._f_dist(flat_obs)
  File "/home/sarv/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/sarv/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/sarv/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Shape mismatch: x has 1 cols (and 11 rows) but y has 11 rows (and 32 cols)
Apply node that caused the error: Dot22(input, hidden_0.W)
Toposort index: 5
Inputs types: [TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(11, 1), (11, 32)]
Inputs strides: [(8, 8), (256, 8)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)](Dot22.0, InplaceDimShuffle{x,0}.0)]]
```

Inserting a line [here](https://github.com/openai/rllab/blob/master/rllab/policies/gaussian_mlp_policy.py#L13) fixes the problem:
 ```python
def get_actions(self, observations):
        flat_obs = self.observation_space.flatten_n(observations)
        flat_obs = flat_obs.transpose() #Inserted this line to fix
        means, log_stds = self._f_dist(flat_obs)
        rnd = np.random.normal(size=means.shape)
        actions = rnd * np.exp(log_stds) + means
        return actions, dict(mean=means, log_std=log_stds)
```

**Comment by dementrock** [comment]
Hi @sarvjeetsinghghotra, get_actions expects to receive a list of observations rather than a single observation. What should work is `policy.get_actions([o])`.
