### ISSUE TITLE
Environment crash during training

### ISSUE THREAD

**Issue by gyang1011** [openai/rllab#87]
Hello,

I am trying to use CEM algorithm to train Lunar Lander - V2. Here is my script:

    from rllab.algos.cem import CEM
    from rllab.baselines.linear_feature_baseline import LinearFeatureBaseline
    from rllab.envs.gym_env import GymEnv
    from rllab.envs.normalized_env import normalize
    from rllab.misc.instrument import run_experiment_lite
    from rllab.policies.categorical_mlp_policy import CategoricalMLPPolicy

    def run_task(*_):
        env = GymEnv("LunarLander-v2")

        policy = CategoricalMLPPolicy(
            env_spec=env.spec,
        
            hidden_sizes=(32, 32)
        )

        baseline = LinearFeatureBaseline(env_spec=env.spec)

  

        algo = CEM(
        env=env,
        policy=policy,
        baseline=baseline,
        n_itr=400,
        discount=0.99,
        )
        algo.train()

    run_experiment_lite(
        run_task,
        # Number of parallel workers for sampling
        n_parallel=2,
        # Only keep the snapshot parameters for the last iteration
        snapshot_mode="last",
        # Specifies the seed for the experiment. If this is not provided, a random seed
        # will be used
        seed=1,
        # plot=True,
    )

And here is the error I have received:

        self._before_reset()
      File "/home/xx/anaconda3/envs/rllab3/lib/python3.5/site-packages/gym/wrappers/monitoring.py", line    190, in _before_reset
        self.stats_recorder.before_reset()
      File "/home/xx/anaconda3/envs/rllab3/lib/python3.5/site-packages/gym/monitoring/stats_recorder.py", line 68, in before_reset
        raise error.Error("Tried to reset environment which is not done. While the monitor is active for {}, you  cannot call reset() unless the episode is over.".format(self.env_id))
    gym.error.Error: Tried to reset environment which is not done. While the monitor is active for LunarLander-v2, you cannot call reset() unless the episode is over.

**Comment by dementrock** [comment]
Hi @gyang1011, when creating GymEnv, set force_reset to True.

**Comment by gyang1011** [comment]
Hi! After I made the change, the new error appears:

      File "/home/xx/Documents/rllab/rllab/envs/gym_env.py", line 10, in <module>
      monitor_logger.setLevel(logging.WARNING)
    NameError: name 'logging' is not defined
    [2017-02-25 22:26:09,476] Making new env: LunarLander-v2
     [2017-02-25 22:26:09,677] Creating monitor directory      /home/xx/Documents/rllab/data/local/experiment/experiment_2017_02_25_22_26_08_0001/gym_log
    2017-02-25 22:26:10.049284 EST | [experiment_2017_02_25_22_26_08_0001] Populating workers...
    Traceback (most recent call last):
        File "/home/xx/Documents/rllab/rllab/envs/gym_env.py", line 10, in <module>
         monitor_logger.setLevel(logging.WARNING)
        Traceback (most recent call last):
         File "/home/xx/Documents/rllab/rllab/envs/gym_env.py", line 10, in <module>
         monitor_logger.setLevel(logging.WARNING)
        NameError: name 'logging' is not defined
        NameError: name 'logging' is not defined
        [2017-02-25 22:26:10,095] Making new env: LunarLander-v2
        [2017-02-25 22:26:10,095] Making new env: LunarLander-v2

**Comment by dementrock** [comment]
@gyang1011 can you update to latest rllab?
